### ISSUE TITLE
set_train_data returns "Size mismatch. All items must be of the same size"

### ISSUE THREAD

**Issue by ksuszka** [FutureLinkCorporation/fann2#1]
Following fragment of code:

    data = libfann.training_data()
    data.set_train_data([[0]],[[0]])

gives "ValueError: Size mismatch. All items must be of the same size" error.

Shouldn't [this condition](https://github.com/FutureLinkCorporation/fann2/blob/master/fann2/fann2.i#L111) be negated?

**Comment by acba** [comment]
Please, update pip package.

I spent an unnecessary time until i realize that i had to clone git and compile it myself.
Verified .i file and saw it right, took some time to notice pip could be outdated.

thanks for solution.
