### ISSUE TITLE
Not able to import FANN into python

### ISSUE THREAD

**Issue by maxkoe** [FutureLinkCorporation/fann2#10]
Hello,

when I try to import FANN2 (installed into `~.anaconda/lib//python2.7/site-packages/fann2/` via `pip install fann2`) I get the following error

    >>> from fann2 import libfann
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/max/.anaconda/lib/python2.7/site-packages/fann2/__init__.py", line 4, in <module>
        from fann2 import libfann
      File "/home/max/.anaconda/lib/python2.7/site-packages/fann2/libfann.py", line 28, in <module>
        _libfann = swig_import_helper()
      File "/home/max/.anaconda/lib/python2.7/site-packages/fann2/libfann.py", line 24, in swig_import_helper
        _mod = imp.load_module('_libfann', fp, pathname, description)
    ImportError: libdoublefann.so.2: cannot open shared object file: No such file or directory

The same thing happens, when I install it into my python outside of anaconda. The orignal C fann libraries are installed to `\usr\local\lib`, especially also the searched for `libdoublefann.so.2`. 

I work under **Lubuntu 14.04 LTS**

Thanks for any help :)

P.S.: The installation log reads 

    $ pip install fann2
    Collecting fann2
      Using cached fann2-1.0.7.tar.gz
    Installing collected packages: fann2
      Running setup.py install for fann2
    Successfully installed fann2-1.0.7

**Comment by FutureLinkOpenSource** [comment]
Hi, we've seen a similar bug report before. Could you let us know if:

https://github.com/FutureLinkCorporation/fann2/issues?q=is%3Aissue+is%3Aclosed

one of these is unable to resolve your issue? Sorry for not responding sooner.

**Comment by tty02-fl** [comment]
Look at the fann installation instructions in http://leenissen.dk/fann/wp/help/installing-fann/ . You will need set prefix CMAKE_INSTALL_PREFIX and point to your system shared libraries. Then the fann libs compiled will go to that folder and after a proper fann installation the python bindings or other softwares will will be able to use the libs.

**Comment by maxkoe** [comment]
Reinstalling (after two weeks without trying it) now apparently resolved the issue. As I also switched computers and operating systems, and therefor will not test it anymore on the old machine, i'll view this issue as closed.

@tty02-fl : as I did not want to change the default installation path of the C-libraries, I didn't think resetting CMAKE_INSTALL_PREFIX was necessary.

**Comment by binfeng** [comment]
`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` this works for me
