### ISSUE TITLE
Can't install fann2 using pip

### ISSUE THREAD

**Issue by revernus** [FutureLinkCorporation/fann2#11]
The version of Python I'm using is 2.7.9 (64 bit) with pip 1.5.6 on Windows 7 powershell. I'm trying to install the package fann2 1.0.7, but I receive an error. Here is the full output:

http://pastebin.com/jXt4PXip

**Comment by harryzheng1991** [comment]
Got the same problem. I tried to open the c file with VS 2013 and rebuild. Similar errors show up. It seems that VS 2013 doesn't like the source c code?

**Comment by revernus** [comment]
Thanks for your post. I'm not used to VS. Coud you please provide some instructions on how I could solve this problem? Thanks in advance!

**Comment by FutureLinkOpenSource** [comment]
Hey, sorry for not responding sooner. We get a lot of issues opened from Windows users. Could you guys see if one of these:

https://github.com/FutureLinkCorporation/fann2/issues?q=is%3Aissue+is%3Aclosed

helps solve the problem?

**Comment by harryzheng1991** [comment]
It seems we are getting c compiling errors during the installation. I've checked others response. They seem to have different issues...

Here is the log:

------------------------------------------------------------
C:\Python27\Scripts\pip-script.py run on 05/23/15 13:25:13
Downloading/unpacking fann2
  Getting page https://pypi.python.org/simple/fann2/
  URLs to search for versions for fann2:
  * https://pypi.python.org/simple/fann2/
  Analyzing links from page https://pypi.python.org/simple/fann2/
    Found link https://pypi.python.org/packages/source/f/fann2/fann2-1.0.0.tar.gz#md5=b0db8db52ced14067c7ec143a269fb8b (from https://pypi.python.org/simple/fann2/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/f/fann2/fann2-1.0.7.tar.gz#md5=9ea834fba950ab0f6113822bb168330f (from https://pypi.python.org/simple/fann2/), version: 1.0.7
  Using version 1.0.7 (newest of versions: 1.0.7, 1.0.0)
  Downloading from URL https://pypi.python.org/packages/source/f/fann2/fann2-1.0.7.tar.gz#md5=9ea834fba950ab0f6113822bb168330f (from https://pypi.python.org/simple/fann2/)
  Running setup.py (path:c:\users\harry\appdata\local\temp\pip_build_Harry\fann2\setup.py) egg_info for package fann2
    running swig
    running egg_info
    creating pip-egg-info\fann2.egg-info
    writing pip-egg-info\fann2.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\fann2.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\fann2.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\fann2.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info\fann2.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info\fann2.egg-info\SOURCES.txt'
  Source in c:\users\harry\appdata\local\temp\pip_build_harry\fann2 has version 1.0.7, which satisfies requirement fann2
Installing collected packages: fann2
  Running setup.py install for fann2
    Running command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\harry\\appdata\\local\\temp\\pip_build_Harry\\fann2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', 

'\n'), __file__, 'exec'))" install --record c:\users\harry\appdata\local\temp\pip-z9qfpq-record\install-record.txt --single-version-externally-managed --compile
    running swig
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\fann2
    copying fann2\__init__.py -> build\lib.win32-2.7\fann2
    copying fann2\libfann.py -> build\lib.win32-2.7\fann2
    running egg_info
    writing fann2.egg-info\PKG-INFO
    writing top-level names to fann2.egg-info\top_level.txt
    writing dependency_links to fann2.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'fann2.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'fann2.egg-info\SOURCES.txt'
    copying fann2\fann2.i -> build\lib.win32-2.7\fann2
    copying fann2\fann2_wrap.cxx -> build\lib.win32-2.7\fann2
    copying fann2\fann_cpp_subclass.h -> build\lib.win32-2.7\fann2
    running build_ext
    building 'fann2._libfann' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\fann2
    C:\Users\Harry\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DSWIG_COMPILE -I./include -I../include -Iinclude -IC:\Python27\include -IC:\Python27\PC 

/Tpfann2/fann2_wrap.cxx /Fobuild\temp.win32-2.7\Release\fann2/fann2_wrap.obj
    fann2_wrap.cxx
    C:\Users\Harry\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
    ./include\fann_cpp.h(958) : error C2057: expected constant expression
    ./include\fann_cpp.h(958) : error C2466: cannot allocate an array of constant size 0
    ./include\fann_cpp.h(958) : error C2133: 'arr' : unknown size
    ./include\fann_cpp.h(1011) : error C2057: expected constant expression
    ./include\fann_cpp.h(1011) : error C2466: cannot allocate an array of constant size 0
    ./include\fann_cpp.h(1011) : error C2133: 'arr' : unknown size
    ./include\fann_cpp.h(1061) : error C2057: expected constant expression
    ./include\fann_cpp.h(1061) : error C2466: cannot allocate an array of constant size 0
    ./include\fann_cpp.h(1061) : error C2133: 'arr' : unknown size
    fann2/fann2_wrap.cxx(5063) : error C2664: 'FANN::training_data::create_train_from_callback' : cannot convert parameter 4 from 'void (__cdecl *)(unsigned int,unsigned int,unsigned int,fann_type *,fann_type *)' to 'void (__stdcall *)

(unsigned int,unsigned int,unsigned int,fann_type *,fann_type *)'
            This conversion requires a reinterpret_cast, a C-style cast or function-style cast
    error: command 'C:\\Users\\Harry\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\harry\\appdata\\local\\temp\\pip_build_Harry\\fann2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read

().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\harry\appdata\local\temp\pip-z9qfpq-record\install-record.txt --single-version-externally-managed --compile:
    running swig

running install

running build

running build_py

creating build

creating build\lib.win32-2.7

creating build\lib.win32-2.7\fann2

copying fann2\__init__.py -> build\lib.win32-2.7\fann2

copying fann2\libfann.py -> build\lib.win32-2.7\fann2

running egg_info

writing fann2.egg-info\PKG-INFO

writing top-level names to fann2.egg-info\top_level.txt

writing dependency_links to fann2.egg-info\dependency_links.txt

warning: manifest_maker: standard file '-c' not found



reading manifest file 'fann2.egg-info\SOURCES.txt'

reading manifest template 'MANIFEST.in'

writing manifest file 'fann2.egg-info\SOURCES.txt'

copying fann2\fann2.i -> build\lib.win32-2.7\fann2

copying fann2\fann2_wrap.cxx -> build\lib.win32-2.7\fann2

copying fann2\fann_cpp_subclass.h -> build\lib.win32-2.7\fann2

running build_ext

building 'fann2._libfann' extension

creating build\temp.win32-2.7

creating build\temp.win32-2.7\Release

creating build\temp.win32-2.7\Release\fann2

C:\Users\Harry\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DSWIG_COMPILE -I./include -I../include -Iinclude -IC:\Python27\include -IC:\Python27\PC 

/Tpfann2/fann2_wrap.cxx /Fobuild\temp.win32-2.7\Release\fann2/fann2_wrap.obj

fann2_wrap.cxx

C:\Users\Harry\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc

./include\fann_cpp.h(958) : error C2057: expected constant expression

./include\fann_cpp.h(958) : error C2466: cannot allocate an array of constant size 0

./include\fann_cpp.h(958) : error C2133: 'arr' : unknown size

./include\fann_cpp.h(1011) : error C2057: expected constant expression

./include\fann_cpp.h(1011) : error C2466: cannot allocate an array of constant size 0

./include\fann_cpp.h(1011) : error C2133: 'arr' : unknown size

./include\fann_cpp.h(1061) : error C2057: expected constant expression

./include\fann_cpp.h(1061) : error C2466: cannot allocate an array of constant size 0

./include\fann_cpp.h(1061) : error C2133: 'arr' : unknown size

fann2/fann2_wrap.cxx(5063) : error C2664: 'FANN::training_data::create_train_from_callback' : cannot convert parameter 4 from 'void (__cdecl *)(unsigned int,unsigned int,unsigned int,fann_type *,fann_type *)' to 'void (__stdcall *)

(unsigned int,unsigned int,unsigned int,fann_type *,fann_type *)'

        This conversion requires a reinterpret_cast, a C-style cast or function-style cast

error: command 'C:\\Users\\Harry\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

----------------------------------------
Cleaning up...
  Removing temporary dir c:\users\harry\appdata\local\temp\pip_build_Harry...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\harry\\appdata\\local\\temp\\pip_build_Harry\\fann2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), 

__file__, 'exec'))" install --record c:\users\harry\appdata\local\temp\pip-z9qfpq-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\harry\appdata\local\temp\pip_build_Harry

\fann2
Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 284, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1450, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pip\req.py", line 721, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "C:\Python27\lib\site-packages\pip\util.py", line 700, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\harry\\appdata\\local\\temp\\pip_build_Harry\\fann2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace

('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\harry\appdata\local\temp\pip-z9qfpq-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\harry\appdata\local\t

**Comment by tty02-fl** [comment]
Se how this user solve the problem: https://github.com/FutureLinkCorporation/fann2/issues/9#issuecomment-99138464

Here you will find how install properly the fann libs http://leenissen.dk/fann/wp/help/installing-fann/ 

Anyway if you find hard the installation you can use a web site that has a working binary of python fann2 v1.07
http://www.lfd.uci.edu/~gohlke/pythonlibs/#fann2

**Comment by harryzheng1991** [comment]
thanks man. I'll give #9 a shot again and try that binary as well. hopefully they will work~

**Comment by revernus** [comment]
If #9 works, I think this is a bug that should be fixed by developers and not a workaround every user who needs to use fann2 should perform, right?

**Comment by revernus** [comment]
#9 didn't work for me. I managed to solve the problem by installing the *.whl file available in http://www.lfd.uci.edu/~gohlke/pythonlibs/#fann2

First I installed wheel:
> pip install wheel

Then I installed the file "fann2‑1.0.7‑cp27‑none‑win32.whl" I downloaded:
> pip install c:\path\to\file\fann2‑1.0.7‑cp27‑none‑win32.whl

Now fann2 is working, it seems. Please fix this bug.

**Comment by FiniteElementries** [comment]
hey guys! sorry came back too late. I've got it working with Revernus's method! Though I didn't install wheel. went straight ahead for the whl file. Cheers! Thanks guys.

**Comment by houssainy** [comment]
I was facing the same problem and it have been solved by using Revernus method also.

Thank you Revernus!

**Comment by revernus** [comment]
I'm glad it helped you, guys. I hope developers fix this bug soon, FANN is a great library.

**Comment by FutureLinkOpenSource** [comment]
We don't build, test, and deploy on Windows; though, when there's time, I'd like to look into that build error posted. It seems easy enough to fix. Resorting to unsigned third-party binaries isn't an ideal solution for users of this package. I'll see if I can get my Windows machine ready to test this and have something sorted by the end of next month.

**Comment by Byreviero** [comment]
I have got the same problem, like FiniteElementries. http://pastebin.com/Tjf6MCdi
I think, the problem is in invalid cast at generated fann2_wrap.cxx by swig. 
In addition, it swears on its includes. If I replaced these by includes from FANN-2.2.0-Source, such errors no longer occur.
Used swigwin-3.0.7

**Comment by magiclevinho** [comment]
Is there a solution to install fann2 from pip? None of the above mentioned solutions worked for me. :(

**Comment by johanvandegriff** [comment]
@magiclevinho See this issue: https://github.com/FutureLinkCorporation/fann2/issues/25
I ended up cloning and installing this fork that has a fix: https://github.com/randomstuff/fann2
