### ISSUE TITLE
/usr/bin/ld: cannot find -ldoublefann

### ISSUE THREAD

**Issue by weich97** [FutureLinkCorporation/fann2#17]
When I install fann2 on a cluster (without administrative permission) using "pip install fann2", I have this kind of error:

[weich97@nrlogin1 aoe]$ ./bin/pip install fann2
Collecting fann2
  Using cached fann2-1.0.7.tar.gz
Installing collected packages: fann2
  Running setup.py install for fann2 ... error
    Complete output from command /home/weich97/aoe/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_aLRo6/fann2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ZifqbX-record/install-record.txt --single-version-externally-managed --compile:
    running swig
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/fann2
    copying fann2/__init__.py -> build/lib.linux-x86_64-2.7/fann2
    copying fann2/libfann.py -> build/lib.linux-x86_64-2.7/fann2
    running egg_info
    writing fann2.egg-info/PKG-INFO
    writing top-level names to fann2.egg-info/top_level.txt
    writing dependency_links to fann2.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'fann2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'fann2.egg-info/SOURCES.txt'
    copying fann2/fann2.i -> build/lib.linux-x86_64-2.7/fann2
    copying fann2/fann2_wrap.cxx -> build/lib.linux-x86_64-2.7/fann2
    copying fann2/fann_cpp_subclass.h -> build/lib.linux-x86_64-2.7/fann2
    running build_ext
    building 'fann2._libfann' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/fann2
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DSWIG_COMPILE -I./include -I../include -Iinclude -I/home/weich97/aoe/include/python2.7 -c fann2/fann2_wrap.cxx -o build/temp.linux-x86_64-2.7/fann2/fann2_wrap.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    g++ -pthread -shared build/temp.linux-x86_64-2.7/fann2/fann2_wrap.o -ldoublefann -o build/lib.linux-x86_64-2.7/fann2/_libfann.so
    /usr/bin/ld: cannot find -ldoublefann
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
    
    ----------------------------------------
Command "/home/weich97/aoe/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_aLRo6/fann2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ZifqbX-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_aLRo6/fann2/

I guess it is fann2 does not find the proper library, but I am not sure. Actually, I have successfully installed fann before fann2. I used "make runtest" and it returned correct information. Hope someone could help me figure out this issue. Thank you very much!

**Comment by angelmadames** [comment]
@weich97 Try reinstalling FANN using cmake, after that, verify where doublefann is installed. You could try {soft/hard}-linking that file into one of the directories used by GCC in your output compile log (ie. -I./include -I../include -Iinclude -I/home/weich97/aoe/include/python2.7 ) and see what happens. For further reference, you could see #6 that address something similar to this. The pip installation has been recently tested with python3.6, so it should go fine if the prerequisites are properly installed. Let us know the results.

**Comment by weich97** [comment]
@angelmadames  Hi, thanks! I have already got FANN2 installed.

**Comment by angelmadames** [comment]
@weich97 NP, good to know. Do you mind sharing what you did to fix the installation issue? Thanks in advance.

**Comment by weich97** [comment]
@angelmadames I asked help from a technician. The steps are approximately:

1)download git clone https://github.com/libfann/fann.git 2) move into the fann directory cd fann/ 3) define installation directory (customize as you like) export FANN_INSTALL_DIR=$HOME/$SYSNAME/lib/fann 4) load compiler and cmake module purge; module load gcc cmake 5) cmake -D CMAKE_INSTALL_PREFIX:PATH=$FANN_INSTALL_DIR . 6) make install 7)add the library location to the library path export LD_LIBRARY_PATH=$FANN_INSTALL_DIR/lib:$LD_LIBRARY_PATH 8)export PYTHONUSERBASE=/home/pid/cascades/python 9)module load gcc/5.2.0 10) module load swig/3.0.11 11)module load python 12)export SWIG_LIB=/opt/apps/gcc5_2/swig/3.0.11/share/swig/3.0.11 13) [mdahshan@nrlogin1 fann]$ pip install fann2 --global-option=build_ext --global-option="-L/home/mdahshan/newriver/lib/fann/lib" --user /opt/apps/gcc5_2/python/2.7.10/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py:199: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options. cmdoptions.check_install_build_global(options) Collecting fann2 Using cached fann2-1.0.7.tar.gz Installing collected packages: fann2 Running setup.py install for fann2 Successfully installed fann2-1.0.7

**Comment by angelmadames** [comment]
Nice! That is a way better approach to fix the problem :)
Thanks for sharing @weich97.

**Comment by weich97** [comment]
@angelmadames No problem. Thank you for answering this question!
