### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by bemcdonnell** [FutureLinkCorporation/fann2#19]
@FutureLinkOpenSource, I would really like to use this package but I'm having trouble finding clear documentation.  Are there any nice examples/tutorials available?

**Comment by FutureLinkOpenSource** [comment]
Have you checked the [Fann forum](https://sourceforge.net/p/fann/discussion/search/?q=python)?

**Comment by bemcdonnell** [comment]
Thanks for the info!
