### ISSUE TITLE
Error when importing libfann; missing symbol

### ISSUE THREAD

**Issue by cLupus** [FutureLinkCorporation/fann2#8]
Have installed fann (2.2.0) from source on Mac OS X 10.10, and fann2 for python 2.7.9 with anaconda through pip.

```python
In [1]: from fann2 import libfann
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e54a7950b430> in <module>()
----> 1 from fann2 import libfann

/Users/sindrenistad/anaconda/lib/python2.7/site-packages/fann2/__init__.py in <module>()
      2 # Fast Artificial Neural Network library for Python
      3 #
----> 4 from fann2 import libfann
      5 __all__ = [
      6     'libfann'

/Users/sindrenistad/anaconda/lib/python2.7/site-packages/fann2/libfann.py in <module>()
     26                 fp.close()
     27             return _mod
---> 28     _libfann = swig_import_helper()
     29     del swig_import_helper
     30 else:

/Users/sindrenistad/anaconda/lib/python2.7/site-packages/fann2/libfann.py in swig_import_helper()
     22         if fp is not None:
     23             try:
---> 24                 _mod = imp.load_module('_libfann', fp, pathname, description)
     25             finally:
     26                 fp.close()

ImportError: dlopen(/Users/*user*/anaconda/lib/python2.7/site-packages/fann2/_libfann.so, 2): Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/sindrenistad/anaconda/lib/python2.7/site-packages/fann2/_libfann.so
  Expected in: /usr/lib/libstdc++.6.dylib
```

**Comment by tty02-fl** [comment]
Can you write here the output of:
otool -L /Users/user/anaconda/lib/python2.7/site-packages/fann2/_libfann.so

**Comment by cLupus** [comment]
libdoublefann.2.dylib (compatibility version 2.0.0, current version 2.2.0)
@rpath/./libstdc++.6.dylib (compatibility version 7.0.0, current version 7.18.0)
/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 283.0.0)
/Users/*user*/anaconda/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

**Comment by tty02-fl** [comment]
We know that python bindings was tested and work fine in Mac OS X 10.9. Probably you should review the installation procedure. The FANN 2.2.0 source code (http://sourceforge.net/projects/fann/files/fann/2.2.0/FANN-2.2.0-Source.zip/download) should be compiled properly an the result libs should be accessible in the system, before proceed to install the python bindings (pip install fann).

**Comment by cLupus** [comment]
Thanks.
After reinstalling it a few times, both from source and from pip, it works.
